# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z010clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/elspencerano/fpga-refresh/project_1/project_1.cache/wt [current_project]
set_property parent.project_path /home/elspencerano/fpga-refresh/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib /home/elspencerano/fpga-refresh/project_1/project_1.srcs/sources_1/new/Hello_world.v
read_xdc /home/elspencerano/fpga-refresh/project_1/project_1.srcs/constrs_1/new/Hello_world.xdc
set_property used_in_implementation false [get_files /home/elspencerano/fpga-refresh/project_1/project_1.srcs/constrs_1/new/Hello_world.xdc]

synth_design -top Hello_world -part xc7z010clg400-1
write_checkpoint -noxdef Hello_world.dcp
catch { report_utilization -file Hello_world_utilization_synth.rpt -pb Hello_world_utilization_synth.pb }
